CREATE SCHEMA public;

CREATE TABLE customer (
  customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  first_name text,
  last_name text,
  email text,
  password text,
  address text,
  phone_number text
);

CREATE TABLE product (
  product_id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_name text,
  sku text,
  description text,
  inventory_level integer,
  cost_price money,
  retail_price money,
  catagory_id integer
);

CREATE TABLE catagory (
  catagory_id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  name text
);

CREATE TABLE "order" (
  order_id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  order_date date,
  total_price money,
  customer_id integer,
  shipment_id integer,
  payment_id integer
);

CREATE TABLE order_item (
  order_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id integer,
  quantity integer,
  price money,
  order_id integer
);

CREATE TABLE payment (
  payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  payment_date date,
  payment_method text,
  amount money,
  customer_id integer
);

CREATE TABLE shipment (
  shipment_id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  shipment_date date,
  address text,
  city text,
  county text,
  country text,
  postal_code text,
  customer_id integer
);

CREATE TABLE cart (
  cart_id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  quantity integer,
  customer_id integer,
  product_id integer
);

ALTER TABLE product ADD FOREIGN KEY (catagory_id) REFERENCES catagory (catagory_id);

ALTER TABLE "order" ADD FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

ALTER TABLE "order" ADD FOREIGN KEY (shipment_id) REFERENCES shipment (shipment_id);

ALTER TABLE "order" ADD FOREIGN KEY (payment_id) REFERENCES payment (payment_id);

ALTER TABLE order_item ADD FOREIGN KEY (product_id) REFERENCES product (product_id);

ALTER TABLE order_item ADD FOREIGN KEY (order_id) REFERENCES "order" (order_id);

ALTER TABLE payment ADD FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

ALTER TABLE shipment ADD FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

ALTER TABLE cart ADD FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

ALTER TABLE cart ADD FOREIGN KEY (product_id) REFERENCES product (product_id);



ALTER SCHEMA public RENAME TO ecoms;